name: test workflow
on: push

jobs:
  my-job:
    name: test workflow start
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        NAME: egoLink
      run: |
        echo $MY_VAR $NAME.